services:
  notifications-service:
    image: notifications-service
    build:
      context: .
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://79.174.80.223:5432/notifications
      SPRING_DATASOURCE_USERNAME: network
      SPRING_DATASOURCE_PASSWORD: dreamteam777*
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 79.174.80.223:9092
      SPRING_FLYWAY_ENABLED: "true"
      SPRING_FLYWAY_LOCATIONS: classpath:db/flyway
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"

    networks:
      - kafka-docker_kafka-net
      - microservice-network
      - teamcity_default

networks:
  kafka-docker_kafka-net:
    external: true
  microservice-network:
    external: true
  teamcity_default:
    external: true